import sys
import os

# You may need to update this path to your specific virtual environment's python executable
# generated by Hostinger's "Setup Python App" tool. It typically looks like:
# /home/u123456789/virtualenv/your_app/3.x/bin/python
# If the app fails to start, uncomment and set the INTERP variable below:
# INTERP = os.path.expanduser("/path/to/your/virtualenv/bin/python")
# if sys.executable != INTERP:
#     os.execl(INTERP, INTERP, *sys.argv)

# Add the current directory to the path so the 'app' module can be found
sys.path.insert(0, os.path.dirname(__file__))

from app.main import app as fastapi_app
from a2wsgi import ASGIMiddleware

# Phusion Passenger looks for the 'application' callable
application = ASGIMiddleware(fastapi_app)
